# Generated by Django 3.1 on 2021-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts2pstransfer',
            name='sub_type',
            field=models.IntegerField(choices=[(4, 'TS to PS (Single Degree)'), (5, 'PS-TS to PS-PS (Dual Degree)'), (6, 'TS-TS to TS-PS (Dual Degree)')]),
        ),
    ]
